version: '2'
services:
  # sensor_temperature:
  #   build: ./sensor_temperature
  #   restart: unless-stopped
  #   privileged: true
  #   network_mode: "host"
  #   labels:
  #     io.balena.features.kernel-modules: '1'
  # buzzer:
  #   build: ./actor_buzzer
  #   restart: no
  #   privileged: true
  #   network_mode: "host"
  #   labels:
  #     io.balena.features.kernel-modules: '1'
  # led:
  #   build: ./actor_led
  #   restart: no
  #   privileged: true
  #   network_mode: "host"
  #   labels:
  #     io.balena.features.kernel-modules: '1'
  # sensor_microphone:
  #   build: ./sensor_microphone
  #   restart: no
  #   privileged: true
  #   network_mode: "host"
  #   labels:
  #     io.balena.features.kernel-modules: '1'
  camera:
    build: ./sensor_camera
    restart: no
    privileged: true
    network_mode: "host"
    labels:
      io.balena.features.kernel-modules: '1'
